import proguard.gradle.ProGuardTask

apply plugin: 'java'
apply plugin: 'maven-publish'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

base {
    archivesName = 'carballo-jse'
}

dependencies {
    implementation project(':core')
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.13.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.4'
}

tasks.register('proguard', ProGuardTask) {
    dependsOn('jar')
    ext {
        obfuscatedJar = "./carballo-${version}.jar"
    }
    injars jar.archiveFile.get()
    injars configurations.runtimeClasspath
    outjars ext.obfuscatedJar
    libraryjars "${System.getProperty('java.home')}/jmods"
    optimizationpasses 5
    allowaccessmodification()
    dontskipnonpubliclibraryclassmembers()
    target '17'
    keep 'public class com.alonsoruibal.chess.uci.Uci { *; }'
    keep 'public class EpdTest { *; }'
    doLast {
        logger.lifecycle "[Proguard] Generated obfuscated JAR in ${ext.obfuscatedJar}"
    }
}

jar {
    manifest.attributes("Main-Class": "com.alonsoruibal.chess.uci.Uci")
}

test {
    ignoreFailures = true
    enableAssertions = true
    testLogging.showStandardStreams = true

    useJUnitPlatform {
        excludeTags 'slow'
    }
}

tasks.register('slowTest', Test) {
    ignoreFailures = true
    enableAssertions = true
    testLogging.showStandardStreams = true

    useJUnitPlatform {
        includeTags 'slow'
    }
}

publishing {
    publications {
        carballoJse(MavenPublication) {
            from components.java
            artifactId = 'carballo-jse'
        }
    }
}