apply plugin: 'java'
apply plugin: 'maven-publish'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

base {
    archivesName = 'carballo-core'
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

assemble.dependsOn sourcesJar

artifacts {
    archives sourcesJar
}

publishing {
    publications {
        carballoCore(MavenPublication) {
            from components.java
            artifactId = 'carballo-core'
            artifact sourcesJar
        }
    }
}